services:
  mongo:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=social_training'
      - 'MONGO_INITDB_ROOT_USERNAME=user'
      - 'MONGO_INITDB_ROOT_PASSWORD=password'
    ports:
      - '27017:27017'
